// Code generated by qtc from "hello.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/hello.qtpl:1
package templates

//line templates/hello.qtpl:1
import "x-dry-go/src/internal/clone_detect"

//line templates/hello.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/hello.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/hello.qtpl:3
func StreamClones(qw422016 *qt422016.Writer, clones map[string][]clone_detect.Clone) {
//line templates/hello.qtpl:3
	qw422016.N().S(`
    `)
//line templates/hello.qtpl:4
	for key, _ := range clones {
//line templates/hello.qtpl:4
		qw422016.N().S(`
        `)
//line templates/hello.qtpl:5
		qw422016.N().U(key)
//line templates/hello.qtpl:5
		qw422016.N().S(`
    `)
//line templates/hello.qtpl:6
	}
//line templates/hello.qtpl:6
	qw422016.N().S(`
`)
//line templates/hello.qtpl:7
}

//line templates/hello.qtpl:7
func WriteClones(qq422016 qtio422016.Writer, clones map[string][]clone_detect.Clone) {
//line templates/hello.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/hello.qtpl:7
	StreamClones(qw422016, clones)
//line templates/hello.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line templates/hello.qtpl:7
}

//line templates/hello.qtpl:7
func Clones(clones map[string][]clone_detect.Clone) string {
//line templates/hello.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/hello.qtpl:7
	WriteClones(qb422016, clones)
//line templates/hello.qtpl:7
	qs422016 := string(qb422016.B)
//line templates/hello.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/hello.qtpl:7
	return qs422016
//line templates/hello.qtpl:7
}

//line templates/hello.qtpl:10
func StreamGreetings(qw422016 *qt422016.Writer, names []string) {
//line templates/hello.qtpl:10
	qw422016.N().S(`
    `)
//line templates/hello.qtpl:11
	qw422016.N().S(` <div id="container"> <h1>Greetings</h1> `)
//line templates/hello.qtpl:15
	if len(names) == 0 {
//line templates/hello.qtpl:15
		qw422016.N().S(` <p>Nobody to greet :(</p> `)
//line templates/hello.qtpl:17
		return
//line templates/hello.qtpl:18
	}
//line templates/hello.qtpl:18
	qw422016.N().S(` <ul> `)
//line templates/hello.qtpl:20
	for i, name := range names {
//line templates/hello.qtpl:20
		qw422016.N().S(` <li>`)
//line templates/hello.qtpl:21
		qw422016.N().D(i)
//line templates/hello.qtpl:21
		qw422016.N().S(` `)
//line templates/hello.qtpl:21
		streamhello(qw422016, name)
//line templates/hello.qtpl:21
		qw422016.N().S(`</li> `)
//line templates/hello.qtpl:22
	}
//line templates/hello.qtpl:22
	qw422016.N().S(` </ul> </div> `)
//line templates/hello.qtpl:26
	qw422016.N().S(`
`)
//line templates/hello.qtpl:27
}

//line templates/hello.qtpl:27
func WriteGreetings(qq422016 qtio422016.Writer, names []string) {
//line templates/hello.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/hello.qtpl:27
	StreamGreetings(qw422016, names)
//line templates/hello.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line templates/hello.qtpl:27
}

//line templates/hello.qtpl:27
func Greetings(names []string) string {
//line templates/hello.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/hello.qtpl:27
	WriteGreetings(qb422016, names)
//line templates/hello.qtpl:27
	qs422016 := string(qb422016.B)
//line templates/hello.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/hello.qtpl:27
	return qs422016
//line templates/hello.qtpl:27
}

//line templates/hello.qtpl:29
func streamhello(qw422016 *qt422016.Writer, name string) {
//line templates/hello.qtpl:29
	qw422016.N().S(`
	Hello, `)
//line templates/hello.qtpl:30
	qw422016.E().S(name)
//line templates/hello.qtpl:30
	qw422016.N().S(`!
`)
//line templates/hello.qtpl:31
}

//line templates/hello.qtpl:31
func writehello(qq422016 qtio422016.Writer, name string) {
//line templates/hello.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/hello.qtpl:31
	streamhello(qw422016, name)
//line templates/hello.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line templates/hello.qtpl:31
}

//line templates/hello.qtpl:31
func hello(name string) string {
//line templates/hello.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/hello.qtpl:31
	writehello(qb422016, name)
//line templates/hello.qtpl:31
	qs422016 := string(qb422016.B)
//line templates/hello.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/hello.qtpl:31
	return qs422016
//line templates/hello.qtpl:31
}
