name: "Finish release"

on:
  push:
    tags:
      - "v*"

jobs:
  Tagged_release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: |
          make build_for_all_platforms version=${{ steps.get_version.outputs.VERSION }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            LICENSE
            build/*

  Build_and_push_Docker_image:
    runs-on: ubuntu-latest
    needs: Tagged_release
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Check out repository code"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_FOR_XDRY_VERSION_UPDATING }}

  Deploy_website:
    runs-on: ubuntu-latest
    needs: Tagged_release
    steps:
      - name: Deploy website
        run: |
          curl -XPOST -u "${{ secrets.DEPLOY_PAT_USERNAME}}:${{secrets.DEPLOY_PAT}}" -H "Accept:application/vnd.github.everest-preview+json" -H "Content-Type:application/json" https://api.github.com/repos/leovie/xdry-website/dispatches --data '{"event_type": "deploy_website" }'